services:
  # Main SQL Database.
  backend_postgres:
    container_name: backend_postgres
    image: postgres:latest
    restart: on-failure
    env_file: ".postgres.env"
    networks:
      - shared-network
    ports:
      - "5433:5432"
    volumes:
      - "postgres-data:/data"

  # Redis database for operating games and caching data.
  backend_redis:
    container_name: backend_redis
    image: redis:latest
    restart: on-failure
    command: "redis-server /usr/local/etc/redis/redis.conf"
    networks:
      - shared-network
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
      - "./redis.conf:/usr/local/etc/redis/redis.conf"

  # S3 storage for managing files.
  backend_minio:
    container_name: backend_minio
    image: minio/minio:latest
    restart: on-failure
    command: server /data --console-address ":9001"
    env_file: ".minio.env"
    networks:
      - shared-network
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio-data:/data"

  # Broker for managing celery tasks.
  backend_rabbitmq:
    container_name: backend_rabbitmq
    image: rabbitmq:3-management
    restart: on-failure
    env_file: ".rabbitmq.env"
    networks:
      - shared-network
    ports:
      - "5672:5672"
      - "5673:15672"
    volumes:
      - "rabbitmq-data:/data"

volumes:
  postgres-data:
  redis-data:
  minio-data:
  rabbitmq-data:

networks:
  shared-network:
    external: true
